#!/usr/bin/env python3
"""
Simple Flask API - generated by clawrissa 😎
"""
from flask import Flask, jsonify, request
from datetime import datetime
import os

app = Flask(__name__)

@app.route('/')
def home():
    return jsonify({
        "message": "Hello from clawrissa's app! 🚀",
        "status": "running",
        "timestamp": datetime.now().isoformat()
    })

@app.route('/health')
def health():
    return jsonify({
        "status": "healthy",
        "time": datetime.now().isoformat()
    })

@app.route('/echo', methods=['POST'])
def echo():
    data = request.get_json() or {}
    return jsonify({
        "echo": data,
        "received_at": datetime.now().isoformat()
    })

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)
